ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER "SALARYHERO" IDENTIFIED BY SALARYHERO;
GRANT ALL PRIVILEGES TO SALARYHERO;
grant execute on DBMS_PIPE to SALARYHERO;
grant execute on DBMS_SYSTEM to SALARYHERO;
grant execute on DBMS_AQ to SALARYHERO;
grant execute on DBMS_CRYPTO to SALARYHERO;
GRANT RESOURCE TO SALARYHERO;
grant execute on dbms_aqadm to SALARYHERO;
grant execute on dbms_aq to SALARYHERO;
grant execute on dbms_aqin to SALARYHERO;
grant execute on dbms_aqjms to SALARYHERO;
GRANT Aq_administrator_role, aq_user_role TO SALARYHERO;
exec dbms_aqadm.grant_system_privilege('ENQUEUE_ANY','SALARYHERO');
exec dbms_aqadm.grant_system_privilege('DEQUEUE_ANY','SALARYHERO');
GRANT CONNECT, RESOURCE, DBA TO SALARYHERO;
GRANT CREATE SESSION TO SALARYHERO;
GRANT UNLIMITED TABLESPACE TO SALARYHERO;
grant create session, create table, create procedure to SALARYHERO;